feat: document plugin type badges
camunda/camunda-modeler-plugin-example pull request #14
Opened 2022-03-17 11:20 UTC by Skaiir

Context:

![image](https://user-images.githubusercontent.com/17801113/158798226-98f65ca8-7555-41ea-9602-35367247ee09.png)

2022-03-17 12:15 UTC, MaxTru requested changes
Would it not be cooler to actually see all the badges?

2022-03-17 16:36 UTC, nikku commented
> Would it not be cooler to actually see all the badges? Perhaps a table or so?

Yes, including MARDOWN markup if possible. Makes it even easier to adopt hem.

2022-03-18 09:45 UTC, MaxTru requested changes

2022-03-18 09:45 UTC, MaxTru commented on README.md
> +  * If your plugin is `BPMN`/`DMN`/`React` but also includes menu entries or styles, just use `BPMN`/`DMN`/`React` in the badge.
Let's simplify

```suggestion
* [ ] Clearly state which Camunda Modeler version your plug-in is compatible with and which type of plugin it is by changing the badges at the top of this README. See [best-practice examples below](#badges-to-indicate-typical-plugin-types).
```

2022-03-22 08:22 UTC, MaxTru requested changes
Can we please consistently use `plugin` instead of `plug-in`. Currently it seems super random which term we use, but `plugin` seems to be the leading one

2022-03-22 13:10 UTC, MaxTru approved these changes

2022-03-22 13:10 UTC, merged